struct Plane
{
    vec3 N;
    float d;
};

layout (std140, set = 0, binding = 0) uniform cb
{
    uint viewportWidth;
    uint viewportHeight;
} gridInfoBuffer;

layout (std140, set = 0, binding = 1) buffer sb
{
    Plane plane[];
} gridData;

layout (local_size_x = 16, local_size_y = 16) in;

void main()
{
    gridData.plane[gl_LocalInvocationIndex].N = vec3(0.0, 1.0, 2.0);
    gridData.plane[gl_LocalInvocationIndex].d = float(gl_LocalInvocationIndex);
}
